resources:
- name: blabbertabber
  type: git
  source:
    uri: https://github.com/blabbertabber/blabbertabber.git
    branch: develop

jobs:
- name: android-test-suite
  plan:
  - get: blabbertabber
    trigger: true
  - task: run-tests
    file: blabbertabber/ci/tasks/run-tests/task.yml
