---
name: concourse

jobs:
- name: concourse
  instances: 1
  resource_pool: concourse_pool
  persistent_disk_pool: database
  templates:
  - {release: concourse,    name: atc}
  - {release: concourse,    name: baggageclaim}
  - {release: concourse,    name: groundcrew}
  - {release: concourse,    name: postgresql}
  - {release: concourse,    name: tsa}
  - {release: garden-linux, name: garden}
  - {release: nginx,        name: nginx}

  networks:
  - name: vip
    # FIXME: replace the IP address with your Elastic IP
    # the Elastic IP must have scope 'vpc' not 'standard'
    # do a global search-replace: the Elastic IP occurs more than once
    # in this manifest
    static_ips: [ &elastic_ip 52.23.10.10 ]
  - name: private
    static_ips: [ *discovery_static_ip ]
    # bosh-init `with multiple networks, a default for 'dns' must be specified`
    # bosh-init `with multiple networks, a default for 'gateway' must be specified`
    default: [ dns, gateway ]
  properties:
    atc:
      basic_auth_username: ci
      # FIXME: replace with a reasonable password
      basic_auth_password: &password heart<3Break
      # FIXME: replace with your server's external URI
      external_url: https://ci.blabbertabber.com
      postgresql:
        # fixes atc not finding "postgresql.service.dc1.consul"
        # enables elimination of consul-agent
        address: 127.0.0.1:5432
        database: *atc-db-name
        role: *atc-db-role
      publicly_viewable: true
    postgresql:
      databases: [ { name: &atc-db-name atc } ]
      roles:
      - &atc-db-role
        name: atc
        password: *password
    tsa:
      forward_host: 127.0.0.1
      authorized_keys:
      # FIXME: paste your worker's public ssh key here (i.e. worker_key.pub)
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqrN3RWjrdcX9PvBYtFzVMXqyOWMlQjgFRu9nKTHv6/lYCLY+1fNigyWd0//YR5IypQtGDs+LwNW+3geUs5q6w5aIOwfNlhFV4AlTnG/tCgrlOlQZaCs8BFchtCmAyX/4ugBiDWW2PO2VH7vf3iZyrO05BzjiHCZIW47ojYN3KIwz8di1maw7ZKSG8TVgPhvLYIGFRIb19po9CTTqq0D6mzsS5BPawxgtzQmNJabdcayCOTf/F9AZU/JNeZlAchEdmUnwDZrzt+86uFh0gNW1yTD5A4Sd3Qs1NptuIvZ3X5a4yulnOnxISzVLQcojjQzB/IW4/MVWCpsddNJTrSVdp cunnie@tara
      atc:
        address: 127.0.0.1:8080
    garden:
      listen_network: tcp
      listen_address: 0.0.0.0:7777
    groundcrew:
      tsa:
        host: 127.0.0.1
      tags:
        - micro
    # FIXME: replace 'ci.blabbertabber.com' with your Concourse Server's FQDN
    # do a global search-replace; there are many occurrences
    nginx_conf: |
      worker_processes  1;
      error_log /var/vcap/sys/log/nginx/error.log   info;
      events {
        worker_connections  1024;
      }
      http {
        include /var/vcap/packages/nginx-1.6.2/conf/mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        keepalive_timeout  65;
        server_names_hash_bucket_size 64;
        # redirect HTTP to HTTPS
        server {
          server_name _; # invalid value which will never trigger on a real hostname.
          listen 80;
          rewrite ^ https://ci.blabbertabber.com$request_uri?;
          access_log /var/vcap/sys/log/nginx/ci.blabbertabber.com-access.log;
          error_log /var/vcap/sys/log/nginx/ci.blabbertabber.com-error.log;
        }
        server {
          server_name ci.blabbertabber.com;
          # weak DH https://weakdh.org/sysadmin.html
          ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
          ssl_prefer_server_ciphers on;
          # poodle https://scotthelme.co.uk/sslv3-goes-to-the-dogs-poodle-kills-off-protocol/
          ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
          listen              443 ssl;
          ssl_certificate     /var/vcap/jobs/nginx/etc/ssl_chained.crt.pem;
          ssl_certificate_key /var/vcap/jobs/nginx/etc/ssl.key.pem;
          access_log /var/vcap/sys/log/nginx/ci.blabbertabber.com-access.log;
          error_log /var/vcap/sys/log/nginx/ci.blabbertabber.com-error.log;
          root /var/vcap/jobs/nginx/www/document_root;
          index index.shtml index.html index.htm;
          # https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-with-ssl-as-a-reverse-proxy-for-jenkins
          location / {
              proxy_set_header        Host $host;
              proxy_set_header        X-Real-IP $remote_addr;
              proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header        X-Forwarded-Proto $scheme;

              # Fix the “It appears that your reverse proxy set up is broken" error.
              proxy_pass          http://localhost:8080;
              proxy_read_timeout  90;

              proxy_redirect      http://localhost:8080 https://ci.blabbertabber.com;
          }

        }
      }
    # FIXME: replace with your HTTPS SSL key
    ssl_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIJKgIBAAKCAgEAqgBtwWIXLHyXqxul7PUVV55qku+yVwbKSHKYtREXYY0i38x6
      ...
      myM8C98VsfoEq1P6QQluTHTKau+VysdPjXLz7t5mG1k6yBPitiszdTChGh+iHg==
      -----END RSA PRIVATE KEY-----
    # FIXME: replace with your HTTPS SSL chained certificate
    ssl_chained_cert: |
      -----BEGIN CERTIFICATE-----
      MIIGYTCCBUmgAwIBAgIRAOFIqgO1kqC+5E0ef2cqXbMwDQYJKoZIhvcNAQELBQAw
      ...
      c2RwQdk=
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIGCDCCA/CgAwIBAgIQKy5u6tl1NmwUim7bo3yMBzANBgkqhkiG9w0BAQwFADCB
      ...
      +AZxAeKCINT+b72x
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIFdDCCBFygAwIBAgIQJ2buVutJ846r13Ci/ITeIjANBgkqhkiG9w0BAQwFADBv
      ...
      pu/xO28QOG8=
      -----END CERTIFICATE-----

disk_pools:
  - name: database
    disk_size: 5120
    cloud_properties:
      type: gp2

resource_pools:
- name: concourse_pool
  network: private
  cloud_properties:
    instance_type: t2.micro
    ephemeral_disk:
      size: 4000
      type: gp2
    availability_zone: us-east-1a
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3126
    sha1: c57c5294a33331d75747bf7593ec8fb822fdd497

networks:
- name: private
  type: manual
  # FIXME: change the following to match your CIDR, e.g. 10.0.0 -> 10.0.16
  subnets:
  - range: 10.0.0.0/24
    reserved: [10.0.0.2 - 10.0.0.9]
    static:
      - &discovery_static_ip 10.0.0.64
    dns: [10.0.0.2]
    gateway: 10.0.0.1
    cloud_properties:
      # FIXME: replace the subnet with your subnet-id
      subnet: subnet-1c90ef6b
- name: vip
  type: vip

cloud_provider:
  template: {name: aws_cpi, release: bosh-aws-cpi}

  ssh_tunnel:
    host: *elastic_ip
    port: 22
    user: vcap
    # FIXME replace with the pathname of your downloaded AWS Key Pair
    # (Power users: no passphrase-protection otherwise you'll see a
    # `asn1: structure error: tags don't match` message when deploying
    #private_key: /Users/cunnie/.ssh/aws_nono.pem
    private_key: ~/.ssh/aws_nono.pem

  # FIXME replace 'a-secret-password' with a secure password
  # also update IP address to match your elastic IP
  mbus: https://nats:a-secret-password@52.23.10.10:6868

  properties:
    aws:
      # FIXME replace with your AWS Access Key
      access_key_id: AKIAxxxxxxxxxxxxxxxx
      # FIXME replace with your AWS Secret
      secret_access_key: 0+B1XW6Vxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      # FIXME replace with your AWS Key Pair name
      default_key_name: aws_nono
      # FIXME replace with your security group
      # the Security Group MUST have the VPC ID of your VPC (e.g. 'vpc-e4250881')
      default_security_groups: [concourse]
      # FIXME replace with your region
      region: us-east-1

    # FIXME: replace 'a-secret-password' with a secure password
    agent: {mbus: "https://nats:a-secret-password@0.0.0.0:6868"}

    blobstore:
      provider: local
      path: /var/vcap/micro_bosh/data/cache

    ntp: [0.north-america.pool.ntp.org]

releases:
- name: concourse
  url: https://bosh.io/d/github.com/concourse/concourse?v=0.67.1
  sha1: 230754680b8ef05c54c9f170c22c1c8c4b8aad5e
- name: bosh-aws-cpi
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?v=36
  sha1: db2a6c6cdd5ff9f77bf083e10118fa72e1f5e181
- name: garden-linux
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/garden-linux-release?v=0.326.0
  sha1: 85b10747926024609b2ba6f6adf59b69e4b724cc
- name: nginx
  url: https://s3.amazonaws.com//nginx-release/nginx-1.tgz
  sha1: e6b3186c0fb3bf7780eccc8d47dba38799d8d108
